@echo off
echo Initializing Git...
git init
echo Adding remote...
git remote add origin https://github.com/Xelent143/streetwear-Expo-Version--Custom-API.git
git remote set-url origin https://github.com/Xelent143/streetwear-Expo-Version--Custom-API.git
echo Staging changes...
git add .
echo Committing...
git commit -m "Update brand identity: Ayzelify logo, hero section, and features"
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
