
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TechPackData } from '../types';

export const exportTechPackPDF = (data: TechPackData, imageUrl: string, quantity: number) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // HEADER
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("CULTUREPIECE | TECHPACK MASTER", 14, 20);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 26);
    doc.text(`Production Quantity: ${quantity} units`, 14, 31);

    // PRODUCT INFO
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 35, pageWidth - 14, 35);

    try {
        doc.addImage(imageUrl, 'PNG', 14, 40, 80, 80, undefined, 'FAST');
    } catch (e) {
        doc.text("[Product Image]", 14, 80);
    }

    // Info (Right of Image)
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(data.productInfo.name, 100, 45);

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Category:", 100, 55);
    doc.setFont("helvetica", "normal");
    doc.text(data.productInfo.category, 130, 55);

    doc.setFont("helvetica", "bold");
    doc.text("Fit/Cut:", 100, 62);
    doc.setFont("helvetica", "normal");
    doc.text(data.productInfo.fitResult, 130, 62);

    doc.setFont("helvetica", "bold");
    doc.text("Fabric:", 100, 69);
    doc.setFont("helvetica", "normal");
    doc.text(data.specs.mainFabric, 130, 69, { maxWidth: 70 });

    // LOGISTICS TABLE
    const unitPhysical = data.specs.estimatedUnitWeightKg;
    const totalPhysical = unitPhysical * quantity;

    autoTable(doc, {
        startY: 90,
        margin: { left: 100 },
        head: [['Logistics / Shipping Spec', 'Value']],
        body: [
            ['Folded Dimensions', `${data.specs.packaging.lengthCm} x ${data.specs.packaging.widthCm} x ${data.specs.packaging.heightCm} cm`],
            ['Unit Physical Wgt', `${unitPhysical.toFixed(2)} kg`],
            [`Total Physical (${quantity})`, `${totalPhysical.toFixed(1)} kg`],
        ],
        theme: 'grid',
        headStyles: { fillColor: [50, 50, 50] },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } }
    });

    // BILL OF MATERIALS (BOM)
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Bill of Materials (BOM)", 14, 150);

    const bomBody = data.bom.map(item => [
        item.component,
        item.specification,
        item.unitConsumption,
        item.totalConsumption
    ]);

    autoTable(doc, {
        startY: 155,
        head: [['Component', 'Specification', 'Unit Cons.', `Total Cons. (${quantity})`]],
        body: bomBody,
        theme: 'grid',
        headStyles: { fillColor: [76, 29, 149] }, // Purple
    });

    // SIZE CHART
    const finalY = (doc as any).lastAutoTable.finalY + 20;

    if (finalY > 250) {
        doc.addPage();
        doc.text("Size Chart (Measurements in inches)", 14, 20);
    } else {
        doc.text("Size Chart (Measurements in inches)", 14, finalY);
    }

    const sizes = Object.keys(data.sizeChart);
    if (sizes.length > 0) {
        // Transpose logic: Rows = Measurements, Cols = Sizes
        // Header: Measurement, S, M, L, XL
        const measurements = Object.keys(Object.values(data.sizeChart)[0] || {});
        const head = ['Measurement', ...sizes];

        // Body: One row per measurement type
        const body = measurements.map(measureKey => {
            const row = [measureKey];
            sizes.forEach(size => {
                row.push(data.sizeChart[size][measureKey]);
            });
            return row;
        });

        autoTable(doc, {
            startY: finalY > 250 ? 25 : finalY + 5,
            head: [head],
            body: body,
            theme: 'striped',
            headStyles: { fillColor: [50, 50, 50] }
        });
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.text(`Page ${i} of ${pageCount} - Generated by CULTUREPIECE Apparels Master`, pageWidth / 2, 290, { align: 'center' });
    }

    doc.save(`${data.productInfo.name.replace(/\s+/g, '_')}_Techpack.pdf`);
};

export const exportSourcingTechPackPDF = (data: any, images: string[]) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // HEADER
    doc.setFillColor(34, 211, 238); // Cyan
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("CULTUREPIECE TECH PACK", 14, 20);

    doc.setFontSize(10);
    doc.text("INDUSTRIAL SOURCING MODULE V1.1", 14, 28);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`STYLE: ${data.productInfo.styleName}`, 140, 15);
    doc.text(`DATE: ${data.productInfo.date}`, 140, 22);
    doc.text(`PROJECT ID: ${data.productInfo.projectId}`, 140, 29);
    doc.text(`QTY: ${data.productInfo.totalQuantity} UNITS`, 140, 36);

    // DESCRIPTION
    let currentY = 50;
    if (data.productInfo.description) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("PRODUCT SUMMARY", 14, currentY);
        currentY += 6;
        doc.setFont("helvetica", "italic");
        doc.setFontSize(9);
        const splitDesc = doc.splitTextToSize(data.productInfo.description, pageWidth - 28);
        doc.text(splitDesc, 14, currentY);
        currentY += (splitDesc.length * 5) + 10;
    }

    // IMAGES (Show first 3 images at the top/middle)
    if (images.length > 0) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("VISUAL ASSETS", 14, currentY);
        currentY += 10;

        const imgSize = (pageWidth - 38) / 3;
        images.slice(0, 3).forEach((img, idx) => {
            try {
                doc.addImage(img, 'JPEG', 14 + (idx * (imgSize + 5)), currentY, imgSize, imgSize * 1.3, undefined, 'FAST');
            } catch (e) {
                doc.rect(14 + (idx * (imgSize + 5)), currentY, imgSize, imgSize * 1.3);
            }
        });
        currentY += (imgSize * 1.3) + 15;
    }

    // MEASUREMENTS TABLE
    const sizeKeys = data.measurements[0]?.sizes ? Object.keys(data.measurements[0].sizes) : [];
    const measureHead = [['Point of Measure', ...sizeKeys]];
    const measureBody = data.measurements.map((m: any) => [
        m.pointsOfMeasure,
        ...sizeKeys.map(s => m.sizes[s])
    ]);

    autoTable(doc, {
        startY: currentY,
        head: measureHead,
        body: measureBody,
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212] },
        styles: { fontSize: 8 },
        didDrawPage: (data) => { currentY = data.cursor?.y || currentY; }
    });
    currentY = (doc as any).lastAutoTable.finalY + 15;

    // BOM TABLE
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("BILL OF MATERIALS (BOM)", 14, currentY);
    currentY += 5;

    autoTable(doc, {
        startY: currentY,
        head: [['Item', 'Description', 'Color/Code', 'Supplier', 'Cons.']],
        body: data.bom.map((b: any) => [b.item, b.description, b.colorCode, b.supplier, b.consumption]),
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212] },
        styles: { fontSize: 8 },
        didDrawPage: (data) => { currentY = data.cursor?.y || currentY; }
    });
    currentY = (doc as any).lastAutoTable.finalY + 15;

    // EMBELLISHMENTS
    if (currentY > 240) { doc.addPage(); currentY = 20; }
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("EMBELLISHMENTS", 14, currentY);
    currentY += 5;

    autoTable(doc, {
        startY: currentY,
        head: [['Type', 'Technique', 'Placement', 'Size', 'Color']],
        body: data.embellishments.map((e: any) => [e.type, e.technique, e.placement, e.size, e.color]),
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212] },
        styles: { fontSize: 8 },
        didDrawPage: (data) => { currentY = data.cursor?.y || currentY; }
    });
    currentY = (doc as any).lastAutoTable.finalY + 15;

    // NOTES & QC
    if (currentY > 200) { doc.addPage(); currentY = 20; }

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("CONSTRUCTION NOTES", 14, currentY);
    currentY += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    data.constructionNotes.forEach((n: string) => {
        doc.text(`- ${n}`, 14, currentY);
        currentY += 4;
    });

    currentY += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("QC CHECKLIST", 14, currentY);
    currentY += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    data.qcChecklist.forEach((q: string) => {
        doc.text(`[ ] ${q}`, 14, currentY);
        currentY += 4;
    });

    currentY += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("CUSTOMIZATION REQUESTS", 14, currentY);
    currentY += 6;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(data.customizationRequests || "None", 14, currentY, { maxWidth: 180 });

    // REMAINDER IMAGES
    if (images.length > 3) {
        doc.addPage();
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("ADDITIONAL REFERENCE IMAGES", 14, 20);

        let imgX = 14;
        let imgY = 30;
        const addImgSize = 90;

        images.slice(3).forEach((img, idx) => {
            if (imgY + addImgSize > 280) {
                doc.addPage();
                imgY = 20;
            }
            try {
                doc.addImage(img, 'JPEG', imgX, imgY, addImgSize, addImgSize * 1.3, undefined, 'FAST');
                imgX = imgX === 14 ? 108 : 14;
                if (imgX === 14) imgY += (addImgSize * 1.3) + 10;
            } catch (e) { }
        });
    }

    doc.save(`${data.productInfo.styleName}_TechPack.pdf`);
};
